### ISSUE TITLE
click to scroll

### ISSUE THREAD

**Issue by horusra** [tensei/HentaiViewer#1]
I much rather just use the scroll wheel on my mouse to scroll. Right now I have to toggle "Click to scroll" off every single time I open something. There should be an option to have it off by default!

**Comment by tensei** [comment]
sure i'll make it save

**Comment by horusra** [comment]
Thanks!. Also it would be great if there was an option to remember the viewer's (pages) window size. So if I open something, then maximize or make the window half of my screen's size, and then close it, that it would have this same size and position when I open something else after that.
Also, auto fetch (instead of clicking fetch) option would be great too.

Great work by the way!
